[package]
name = "blsttc"
version = "4.0.0"
authors = [
  "Vladimir Komendantskiy <komendantsky@gmail.com>",
  "Andreas Fackler <AndreasFackler@gmx.de>",
  "Peter van Nostrand <jnz@riseup.net>",
  "Andrew Gross <andogro@gmail.com>",
  "Nick Sanders <nsan1129@gmail.com>",
  "Marc Brinkmann <git@marcbrinkmann.de>"
]
categories = [ "cryptography" ]
keywords = [ "pairing", "threshold" ]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/maidsafe/blsttc"
description = "Pairing threshold cryptography"
edition = "2018"

[dependencies]
byteorder = "1.3.4"
hex_fmt = "0.3.0"
log = "0.4.8"
rand = "0.7.3"
rand_chacha = "0.2.2"
thiserror = "1.0.22"
zeroize = "1.1.0"

  [dependencies.blst]
  version = "0.3.5"
  features = [ "portable" ]

  [dependencies.serde]
  version = "1.0.104"
  features = [ "derive" ]

  [dependencies.tiny-keccak]
  version = "2.0.1"
  features = [ "sha3" ]

[dev-dependencies]
criterion = "0.3.1"
eyre = "0.6.5"
hex = "0.4.3"
rand_xorshift = "0.2.0"

[[bench]]
name = "bench"
harness = false
